# TEST 4
language: python

python:
  - 2.7

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq libnetcdf-dev gfortran

script:
 - pwd
 - cd ..
 - git clone git://github.com/genie-model/cgenie-data.git
 - git clone git://github.com/genie-model/cgenie-test.git
 - cd cgenie
 - root=`pwd`
 - echo "cgenie_root: ${root}" > ~/.cgenierc
 - echo "cgenie_data: ${root/cgenie/cgenie-data}" >> ~/.cgenierc
 - echo "cgenie_test: ${root/cgenie/cgenie-test}" >> ~/.cgenierc
 - echo "cgenie_jobs: ${root/cgenie/cgenie-jobs}" >> ~/.cgenierc
 - echo "cgenie_version: DEVELOPMENT" >> ~/.cgenierc
 - ./tests run basic
