# TEST 4
language: python

python:
  - 2.7

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq libnetcdf-dev gfortran

script:
 - pwd
 - cd ..
 - git clone git://github.com/genie-model/cgenie-data.git
 - git clone git://github.com/genie-model/cgenie-test.git
 - cd cgenie
 - ./tools/travis-setup
 - ./tests run basic
